name: relisa
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter
  http: 1.1.0
  cupertino_icons: ^1.0.0
  carousel_slider: ^4.2.1
  # provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/relisa.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
